[package]
name = "eoka-sdk"
version = "0.3.2"
edition = "2021"
license = "MIT"
description = "Rust SDK for controlling eoka browser automation sessions"
repository = "https://github.com/shrimp-software/eoka-tools"
homepage = "https://github.com/shrimp-software/eoka-tools"
documentation = "https://docs.rs/eoka-sdk"
readme = "README.md"
authors = ["cbxss"]

[dependencies]
anyhow = { workspace = true }
eoka = "0.5.10"
eoka-protocol = { path = "../eoka-protocol", version = "0.2.2" }
tokio = { workspace = true }
